### ISSUE TITLE
[ARM][Raspberry Pi] Failed Entrypoint

### ISSUE THREAD

**Issue by Vibeshibe** [Go2Engle/dynuiuc#15]
Container via docker-compose ends up in a restart loop, logs:

`dynuiuc  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
dynuiuc  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
dynuiuc  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
dynuiuc  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
dynuiuc  | exec /usr/local/bin/docker-entrypoint.sh: exec format error`

Running on ARM and Ubuntu.

**Comment by Vibeshibe** [comment]
Seems to be exclusive to ARM. Running this on my x86 host works flawlessly.

**Comment by Go2Engle** [comment]
> Seems to be exclusive to ARM. Running this on my x86 host works flawlessly.

Tried adding multi-platform support on the docker build and it was failing. After doing a tiny bit of digging it looks like the dynu IP Update Client provided by dynu is only amd64 so fails to install inside the arm container. Sorry =[
